[project]
name = "teoria-kompilacji"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "sly>=0.5",
]
[project.scripts]
run = "main:main"